language: node_js
node_js:
- '0.10'
before_install:
- make install
services:
- mongodb
notifications:
  email:
  - coinsmanager@gmail.com
git:
  submodules: false
deploy:
  provider: heroku
  app: coinsmanager
  api_key:
    secure: FjcbJdgcB1IIug3Qf5oFlF5PHW8LYnIUJCSUEz7GI5i6tVvtye1UvqkA12BP+//u3rtPcO3d33rjNY5/qvIRIdJ/wMKACAHdzRa8jWge2dxW7filynF6LVsh5ezwr7Sq/MgNwvqQcRp7eQNsOlBzdZRyQYE0VAa4fAD1+SZPnWQ=
  on:
    all_branches: true
after_deploy:
- "cd app/client/compass && compass compile && cd -"
#- for file in `find . -name "*css"`; do git add -f $file; done; git ci -am "heroku style"
- "cd app/ && meteor reset"
- restart
