language: node_js
node_js:
- '0.10'
before_install:
- make install
services:
- mongodb
notifications:
  email:
  - coinsmanager@gmail.com
git:
  submodules: false
deploy:
  provider: heroku
  app:
    master: coinsmanager-alpha
    develop: coinsmanager-beta
  api_key:
    secure: "Ff8+oVLq1sby5ZVcSw3LHNV9hj4euNARI2NyzrP5ZgxXfr3d1cNBdQtkatUiZV3NZvZm05qxNs6ZyvaETPcOSQCNWcn/KfkCD8YCIeTfzkKpPrQdXYYGEqtzn7IVt4stU9V2FHcCc5GalZNFYbyT7mZBw9FjR4hThky/qoDRniI="
  on:
    all_branches: true
after_deploy:
- "cd app/client/compass && compass compile && cd -"
#- cd app/ && meteor reset
- restart
